/*
Package stacksblockchainapi

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
*/
package stacksblockchainapi

import (
	"context"
	"log"
	"net/http"
	"os"

	"github.com/apimatic/go-core-runtime/https"
)

const UserAgent = "APIMATIC 3.0"

// Client is an interface representing the main client for accessing configuration and controllers.
type ClientInterface interface {
	Configuration() *Configuration
	AccountsController() *AccountsController
	BlocksController() *BlocksController
	BurnBlocksController() *BurnBlocksController
	FaucetsController() *FaucetsController
	FeesController() *FeesController
	InfoController() *InfoController
	MicroblocksController() *MicroblocksController
	NamesController() *NamesController
	NonFungibleTokensController() *NonFungibleTokensController
	RosettaController() *RosettaController
	SearchController() *SearchController
	SmartContractsController() *SmartContractsController
	StackingRewardsController() *StackingRewardsController
	TransactionsController() *TransactionsController
	MempoolController() *MempoolController
	StackingController() *StackingController
}

// client is an implementation of the Client interface.
type client struct {
	callBuilderFactory          https.CallBuilderFactory
	configuration               Configuration
	accountsController          AccountsController
	blocksController            BlocksController
	burnBlocksController        BurnBlocksController
	faucetsController           FaucetsController
	feesController              FeesController
	infoController              InfoController
	microblocksController       MicroblocksController
	namesController             NamesController
	nonFungibleTokensController NonFungibleTokensController
	rosettaController           RosettaController
	searchController            SearchController
	smartContractsController    SmartContractsController
	stackingRewardsController   StackingRewardsController
	transactionsController      TransactionsController
	mempoolController           MempoolController
	stackingController          StackingController
	errorLog                    *log.Logger
	infoLog                     *log.Logger
}

// NewClient is the constructor for creating a new client instance.
// It takes a Configuration object as a parameter and returns the Client interface.
func NewClient(configuration Configuration) ClientInterface {
	infoLog := log.New(os.Stdout, "INFO\t", log.Ldate|log.Ltime)
	errorLog := log.New(os.Stderr, "ERROR\t", log.Ldate|log.Ltime|log.Lshortfile)

	client := &client{
		configuration: configuration,
		infoLog:       infoLog,
		errorLog:      errorLog,
	}

	client.callBuilderFactory = callBuilderHandler(
		func(server string) string {
			if server == "" {
				server = "default"
			}
			baseUri := getBaseUri(Server(server), client.configuration)
			client.infoLog.Printf("base uri: %s \n", baseUri)
			return baseUri
		},
		nil,
		https.NewHttpClient(configuration.HttpConfiguration()),
		configuration.httpConfiguration.RetryConfiguration(),
		withUserAgent(UserAgent),
	)

	baseController := NewBaseController(client)
	client.accountsController = *NewAccountsController(*baseController)
	client.blocksController = *NewBlocksController(*baseController)
	client.burnBlocksController = *NewBurnBlocksController(*baseController)
	client.faucetsController = *NewFaucetsController(*baseController)
	client.feesController = *NewFeesController(*baseController)
	client.infoController = *NewInfoController(*baseController)
	client.microblocksController = *NewMicroblocksController(*baseController)
	client.namesController = *NewNamesController(*baseController)
	client.nonFungibleTokensController = *NewNonFungibleTokensController(*baseController)
	client.rosettaController = *NewRosettaController(*baseController)
	client.searchController = *NewSearchController(*baseController)
	client.smartContractsController = *NewSmartContractsController(*baseController)
	client.stackingRewardsController = *NewStackingRewardsController(*baseController)
	client.transactionsController = *NewTransactionsController(*baseController)
	client.mempoolController = *NewMempoolController(*baseController)
	client.stackingController = *NewStackingController(*baseController)
	client.infoLog.Println("setting up client")
	return client
}

// Configuration returns the configuration instance of the client.
func (c *client) Configuration() *Configuration {
	return &c.configuration
}

// AccountsController returns the accountsController instance of the client.
func (c *client) AccountsController() *AccountsController {
	return &c.accountsController
}

// BlocksController returns the blocksController instance of the client.
func (c *client) BlocksController() *BlocksController {
	return &c.blocksController
}

// BurnBlocksController returns the burnBlocksController instance of the client.
func (c *client) BurnBlocksController() *BurnBlocksController {
	return &c.burnBlocksController
}

// FaucetsController returns the faucetsController instance of the client.
func (c *client) FaucetsController() *FaucetsController {
	return &c.faucetsController
}

// FeesController returns the feesController instance of the client.
func (c *client) FeesController() *FeesController {
	return &c.feesController
}

// InfoController returns the infoController instance of the client.
func (c *client) InfoController() *InfoController {
	return &c.infoController
}

// MicroblocksController returns the microblocksController instance of the client.
func (c *client) MicroblocksController() *MicroblocksController {
	return &c.microblocksController
}

// NamesController returns the namesController instance of the client.
func (c *client) NamesController() *NamesController {
	return &c.namesController
}

// NonFungibleTokensController returns the nonFungibleTokensController instance of the client.
func (c *client) NonFungibleTokensController() *NonFungibleTokensController {
	return &c.nonFungibleTokensController
}

// RosettaController returns the rosettaController instance of the client.
func (c *client) RosettaController() *RosettaController {
	return &c.rosettaController
}

// SearchController returns the searchController instance of the client.
func (c *client) SearchController() *SearchController {
	return &c.searchController
}

// SmartContractsController returns the smartContractsController instance of the client.
func (c *client) SmartContractsController() *SmartContractsController {
	return &c.smartContractsController
}

// StackingRewardsController returns the stackingRewardsController instance of the client.
func (c *client) StackingRewardsController() *StackingRewardsController {
	return &c.stackingRewardsController
}

// TransactionsController returns the transactionsController instance of the client.
func (c *client) TransactionsController() *TransactionsController {
	return &c.transactionsController
}

// MempoolController returns the mempoolController instance of the client.
func (c *client) MempoolController() *MempoolController {
	return &c.mempoolController
}

// StackingController returns the stackingController instance of the client.
func (c *client) StackingController() *StackingController {
	return &c.stackingController
}

// GetCallBuilder returns the CallBuilderFactory used by the client.
func (c *client) GetCallBuilder() https.CallBuilderFactory {
	return c.callBuilderFactory
}

// getBaseUri returns the base URI based on the server and configuration.
func getBaseUri(
	server Server,
	configuration Configuration) string {
	if configuration.Environment() == Environment(PRODUCTION) {
		if server == Server(ENUMDEFAULT) {
			return "https://api.mainnet.hiro.so/"
		}
	}
	if configuration.Environment() == Environment(ENVIRONMENT2) {
		if server == Server(ENUMDEFAULT) {
			return "https://api.testnet.hiro.so/"
		}
	}
	if configuration.Environment() == Environment(ENVIRONMENT3) {
		if server == Server(ENUMDEFAULT) {
			return "http://localhost:3999/"
		}
	}
	return "TODO: Select a valid server."
}

// clientOptions is a function type representing options for the client.
type clientOptions func(cb https.CallBuilder)

// callBuilderHandler creates the call builder factory with various options.
func callBuilderHandler(
	baseUrlProvider func(server string) string,
	auth https.Authenticator,
	httpClient https.HttpClient,
	retryConfig RetryConfiguration,
	opts ...clientOptions) https.CallBuilderFactory {
	callBuilderFactory := https.CreateCallBuilderFactory(baseUrlProvider, auth, httpClient, retryConfig)
	return tap(callBuilderFactory, opts...)
}

// tap is a utility function to apply client options to the call builder factory.
func tap(
	callBuilderFactory https.CallBuilderFactory,
	opts ...clientOptions) https.CallBuilderFactory {
	return func(ctx context.Context, httpMethod, path string) https.CallBuilder {
		callBuilder := callBuilderFactory(ctx, httpMethod, path)
		for _, opt := range opts {
			opt(callBuilder)
		}
		return callBuilder
	}
}

// withUserAgent is an option to add a user agent header to the HTTP request.
func withUserAgent(userAgent string) clientOptions {
	f := func(request *http.Request) *http.Request {
		request.Header.Add("user-agent", userAgent)
		return request
	}
	return func(cb https.CallBuilder) {
		cb.InterceptRequest(f)
	}
}
