/*
Package stacks

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
*/
package models

// TypeEnum is a string enum.
type TypeEnum string

const (
	TypeEnum_COINBASE         TypeEnum = "coinbase"
	TypeEnum_TOKENTRANSFER    TypeEnum = "token_transfer"
	TypeEnum_SMARTCONTRACT    TypeEnum = "smart_contract"
	TypeEnum_CONTRACTCALL     TypeEnum = "contract_call"
	TypeEnum_POISONMICROBLOCK TypeEnum = "poison_microblock"
	TypeEnum_TENURECHANGE     TypeEnum = "tenure_change"
)

// PostConditionModeEnum is a string enum.
type PostConditionModeEnum string

const (
	PostConditionModeEnum_ALLOW PostConditionModeEnum = "allow"
	PostConditionModeEnum_DENY  PostConditionModeEnum = "deny"
)

// PostConditionFungibleConditionCodeEnum is a string enum.
// A fungible condition code encodes a statement being made for either STX or a fungible token, with respect to the originating account.
type PostConditionFungibleConditionCodeEnum string

const (
	PostConditionFungibleConditionCodeEnum_SENTEQUALTO              PostConditionFungibleConditionCodeEnum = "sent_equal_to"
	PostConditionFungibleConditionCodeEnum_SENTGREATERTHAN          PostConditionFungibleConditionCodeEnum = "sent_greater_than"
	PostConditionFungibleConditionCodeEnum_SENTGREATERTHANOREQUALTO PostConditionFungibleConditionCodeEnum = "sent_greater_than_or_equal_to"
	PostConditionFungibleConditionCodeEnum_SENTLESSTHAN             PostConditionFungibleConditionCodeEnum = "sent_less_than"
	PostConditionFungibleConditionCodeEnum_SENTLESSTHANOREQUALTO    PostConditionFungibleConditionCodeEnum = "sent_less_than_or_equal_to"
)

// TransactionAnchorModeTypeEnum is a string enum.
// `on_chain_only`: the transaction MUST be included in an anchored block, `off_chain_only`: the transaction MUST be included in a microblock, `any`: the leader can choose where to include the transaction.
type TransactionAnchorModeTypeEnum string

const (
	TransactionAnchorModeTypeEnum_ONCHAINONLY  TransactionAnchorModeTypeEnum = "on_chain_only"
	TransactionAnchorModeTypeEnum_OFFCHAINONLY TransactionAnchorModeTypeEnum = "off_chain_only"
	TransactionAnchorModeTypeEnum_ANY          TransactionAnchorModeTypeEnum = "any"
)

// TransactionStatusEnum is a string enum.
// Status of the transaction
type TransactionStatusEnum string

const (
	TransactionStatusEnum_SUCCESS              TransactionStatusEnum = "success"
	TransactionStatusEnum_ABORTBYRESPONSE      TransactionStatusEnum = "abort_by_response"
	TransactionStatusEnum_ABORTBYPOSTCONDITION TransactionStatusEnum = "abort_by_post_condition"
)

// TransactionEventAssetTypeEnum is a string enum.
type TransactionEventAssetTypeEnum string

const (
	TransactionEventAssetTypeEnum_TRANSFER TransactionEventAssetTypeEnum = "transfer"
	TransactionEventAssetTypeEnum_MINT     TransactionEventAssetTypeEnum = "mint"
	TransactionEventAssetTypeEnum_BURN     TransactionEventAssetTypeEnum = "burn"
)

// EventTypeEnum is a string enum.
type EventTypeEnum string

const (
	EventTypeEnum_SMARTCONTRACTLOG EventTypeEnum = "smart_contract_log"
)

// CauseEnum is a string enum.
// Cause of change in mining tenure. Depending on cause, tenure can be ended or extended.
type CauseEnum string

const (
	CauseEnum_BLOCKFOUND CauseEnum = "block_found"
	CauseEnum_EXTENDED   CauseEnum = "extended"
)

// TxTypeEnum is a string enum.
type TxTypeEnum string

const (
	TxTypeEnum_TOKENTRANSFER TxTypeEnum = "token_transfer"
)

// OrderByEnum is a string enum.
type OrderByEnum string

const (
	OrderByEnum_AGE  OrderByEnum = "age"
	OrderByEnum_SIZE OrderByEnum = "size"
	OrderByEnum_FEE  OrderByEnum = "fee"
)

// OrderEnum is a string enum.
type OrderEnum string

const (
	OrderEnum_ASC  OrderEnum = "asc"
	OrderEnum_DESC OrderEnum = "desc"
)

// MempoolTransactionStatusEnum is a string enum.
// Status of the transaction
type MempoolTransactionStatusEnum string

const (
	MempoolTransactionStatusEnum_PENDING                    MempoolTransactionStatusEnum = "pending"
	MempoolTransactionStatusEnum_DROPPEDREPLACEBYFEE        MempoolTransactionStatusEnum = "dropped_replace_by_fee"
	MempoolTransactionStatusEnum_DROPPEDREPLACEACROSSFORK   MempoolTransactionStatusEnum = "dropped_replace_across_fork"
	MempoolTransactionStatusEnum_DROPPEDTOOEXPENSIVE        MempoolTransactionStatusEnum = "dropped_too_expensive"
	MempoolTransactionStatusEnum_DROPPEDSTALEGARBAGECOLLECT MempoolTransactionStatusEnum = "dropped_stale_garbage_collect"
	MempoolTransactionStatusEnum_DROPPEDPROBLEMATIC         MempoolTransactionStatusEnum = "dropped_problematic"
)

// TransferTypeEnum is a string enum.
// Indicates if the transfer is from a stx-transfer transaction or a contract-call transaction
type TransferTypeEnum string

const (
	TransferTypeEnum_BULKSEND        TransferTypeEnum = "bulk-send"
	TransferTypeEnum_STXTRANSFER     TransferTypeEnum = "stx-transfer"
	TransferTypeEnum_STXTRANSFERMEMO TransferTypeEnum = "stx-transfer-memo"
)

// NetworkEnum is a string enum.
type NetworkEnum string

const (
	NetworkEnum_TESTNET NetworkEnum = "testnet"
	NetworkEnum_MAINNET NetworkEnum = "mainnet"
)

// EntityTypeEnum is a string enum.
// Shows the currenty category of entity it is searched in.
type EntityTypeEnum string

const (
	EntityTypeEnum_STANDARDADDRESS EntityTypeEnum = "standard_address"
	EntityTypeEnum_UNKNOWNHASH     EntityTypeEnum = "unknown_hash"
	EntityTypeEnum_CONTRACTADDRESS EntityTypeEnum = "contract_address"
	EntityTypeEnum_INVALIDTERM     EntityTypeEnum = "invalid_term"
)

// CoinActionEnum is a string enum.
// CoinActions are different state changes that a Coin can undergo. When a Coin is created, it is coin_created. When a Coin is spent, it is coin_spent. It is assumed that a single Coin cannot be created or spent more than once.
type CoinActionEnum string

const (
	CoinActionEnum_COINCREATED CoinActionEnum = "coin_created"
	CoinActionEnum_COINSPENT   CoinActionEnum = "coin_spent"
)

// CurveTypeEnum is a string enum.
// CurveType is the type of cryptographic curve associated with a PublicKey.
type CurveTypeEnum string

const (
	CurveTypeEnum_SECP256K1    CurveTypeEnum = "secp256k1"
	CurveTypeEnum_EDWARDS25519 CurveTypeEnum = "edwards25519"
)

// SignatureTypeEnum is a string enum.
// SignatureType is the type of a cryptographic signature.
type SignatureTypeEnum string

const (
	SignatureTypeEnum_ECDSA           SignatureTypeEnum = "ecdsa"
	SignatureTypeEnum_ECDSARECOVERY   SignatureTypeEnum = "ecdsa_recovery"
	SignatureTypeEnum_ED25519         SignatureTypeEnum = "ed25519"
	SignatureTypeEnum_SCHNORR1        SignatureTypeEnum = "schnorr_1"
	SignatureTypeEnum_SCHNORRPOSEIDON SignatureTypeEnum = "schnorr_poseidon"
)

// Type2Enum is a string enum.
type Type2Enum string

const (
	Type2Enum_SMARTCONTRACTLOG      Type2Enum = "smart_contract_log"
	Type2Enum_STXLOCK               Type2Enum = "stx_lock"
	Type2Enum_STXASSET              Type2Enum = "stx_asset"
	Type2Enum_FUNGIBLETOKENASSET    Type2Enum = "fungible_token_asset"
	Type2Enum_NONFUNGIBLETOKENASSET Type2Enum = "non_fungible_token_asset"
)
